// 25 realistic Bangladesh real estate demo properties

export interface SeedProperty {
  title:           string
  description:     string
  price:           number
  price_type:      'sale' | 'rent'
  property_type:   'apartment' | 'villa' | 'plot' | 'office' | 'townhouse' | 'studio' | 'penthouse'
  bedrooms:        number | null
  bathrooms:       number | null
  area_sqft:       number | null
  city:            string
  location:        string
  address:         string
  status:          'available' | 'sold' | 'rented' | 'archived'
  featured:        boolean
  images:          string[]
  video_url:       string | null
  video_type:      'upload' | 'youtube' | null
  whatsapp_number: string
  phone_number:    string
  views_count:     number
  saves_count:     number
}

const WA = '+8801575871170'
const PHONE = '+8801575871170'

// Unsplash property images (free, high-quality, no copyright)
const IMG = {
  apartment: [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=1200&q=80',
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80',
  ],
  villa: [
    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80',
    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
  ],
  penthouse: [
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80',
    'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80',
    'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&q=80',
  ],
  townhouse: [
    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80',
  ],
  studio: [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80',
  ],
  office: [
    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&q=80',
    'https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=1200&q=80',
    'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200&q=80',
  ],
  plot: [
    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=1200&q=80',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
  ],
}

// real property tour videos (copyright-safe channels)
const VIDEOS = {
  luxury:   'https://www.youtube.com/watch?v=VJEbT7-vDdA',
  modern:   'https://www.youtube.com/watch?v=oPimd6Y2m6Y',
}

export const SEED_PROPERTIES: SeedProperty[] = [
  // ─── DHAKA — GULSHAN (premium area) ─────────────────────────────
  {
    title: '[DEMO] Luxurious 4BR Penthouse in Gulshan 2',
    description: 'Stunning penthouse with panoramic city views, private rooftop terrace, and premium finishes throughout. Located in the heart of Gulshan with easy access to embassies, high-end restaurants, and shopping.',
    price: 85000000,
    price_type: 'sale',
    property_type: 'penthouse',
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 4200,
    city: 'Dhaka',
    location: 'Gulshan 2',
    address: 'Road 79, Gulshan 2, Dhaka 1212',
    status: 'available',
    featured: true,
    images: IMG.penthouse.slice(0, 3),
    video_url: VIDEOS.luxury,
    video_type: 'youtube',
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 847,
    saves_count: 62,
  },
  {
    title: '[DEMO] Modern 3BR Apartment in Gulshan 1',
    description: 'Contemporary 3-bedroom apartment with modern kitchen, spacious living area, and dedicated parking. Building has 24/7 security, gym, and rooftop garden.',
    price: 32000000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2200,
    city: 'Dhaka',
    location: 'Gulshan 1',
    address: 'Road 41, Gulshan 1, Dhaka 1212',
    status: 'available',
    featured: true,
    images: IMG.apartment.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 523,
    saves_count: 41,
  },
  {
    title: '[DEMO] Premium Office Space in Gulshan Circle',
    description: 'Grade-A office space with open floor plan, meeting rooms, and executive cabin. Ready for corporate occupancy. Includes 4 dedicated parking spots.',
    price: 850000,
    price_type: 'rent',
    property_type: 'office',
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 3500,
    city: 'Dhaka',
    location: 'Gulshan Circle',
    address: 'Bir Uttam Rafiqul Islam Ave, Gulshan, Dhaka',
    status: 'available',
    featured: false,
    images: IMG.office.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 156,
    saves_count: 12,
  },

  // ─── DHAKA — DHANMONDI ─────────────────────────────
  {
    title: '[DEMO] Spacious 3BR Apartment in Dhanmondi 27',
    description: 'Family-friendly apartment near Dhanmondi Lake. Walking distance to schools, hospitals, and Rabindra Sarobar. South-facing with excellent ventilation.',
    price: 18500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1850,
    city: 'Dhaka',
    location: 'Dhanmondi',
    address: 'Road 27, Dhanmondi, Dhaka 1209',
    status: 'available',
    featured: true,
    images: IMG.apartment.slice(1, 4),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 412,
    saves_count: 33,
  },
  {
    title: '[DEMO] Cozy 2BR Apartment in Dhanmondi 15',
    description: 'Perfect for young families or professionals. Modern kitchen, master bedroom with attached bath. Well-maintained building with lift access.',
    price: 45000,
    price_type: 'rent',
    property_type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1200,
    city: 'Dhaka',
    location: 'Dhanmondi',
    address: 'Road 15, Dhanmondi, Dhaka 1209',
    status: 'rented',
    featured: false,
    images: IMG.apartment.slice(2, 5),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 289,
    saves_count: 18,
  },
  {
    title: '[DEMO] Modern Studio in Dhanmondi 8/A',
    description: 'Fully furnished studio ideal for students or young professionals. Includes kitchenette, wardrobe, and study area. Building has generator backup.',
    price: 22000,
    price_type: 'rent',
    property_type: 'studio',
    bedrooms: null,
    bathrooms: 1,
    area_sqft: 550,
    city: 'Dhaka',
    location: 'Dhanmondi',
    address: 'Road 8/A, Dhanmondi, Dhaka 1209',
    status: 'available',
    featured: false,
    images: IMG.studio.slice(0, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 178,
    saves_count: 21,
  },

  // ─── DHAKA — BANANI / BARIDHARA ─────────────────────────────
  {
    title: '[DEMO] Executive 4BR Apartment in Banani DOHS',
    description: 'Premium apartment in secured DOHS community. Large balconies with garden view, servant quarters, 2 parking spaces. Ideal for executive families.',
    price: 42000000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 2800,
    city: 'Dhaka',
    location: 'Banani DOHS',
    address: 'Road 8, Banani DOHS, Dhaka 1206',
    status: 'available',
    featured: true,
    images: IMG.apartment.slice(3, 6),
    video_url: VIDEOS.modern,
    video_type: 'youtube',
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 621,
    saves_count: 47,
  },
  {
    title: '[DEMO] Diplomatic 5BR Villa in Baridhara',
    description: 'Elegant villa in Diplomatic Zone. Private garden, swimming pool, servant quarters, 3-car garage. Perfect for diplomatic missions or luxury living.',
    price: 180000000,
    price_type: 'sale',
    property_type: 'villa',
    bedrooms: 5,
    bathrooms: 6,
    area_sqft: 6500,
    city: 'Dhaka',
    location: 'Baridhara Diplomatic Zone',
    address: 'Road 11, Baridhara, Dhaka 1212',
    status: 'available',
    featured: true,
    images: IMG.villa.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 934,
    saves_count: 78,
  },
  {
    title: '[DEMO] 3BR Apartment in Banani Road 12',
    description: 'Well-designed apartment in central Banani. Close to Banani Club, restaurants, and shopping malls. Building amenities include gym and community hall.',
    price: 28000000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2000,
    city: 'Dhaka',
    location: 'Banani',
    address: 'Road 12, Banani, Dhaka 1213',
    status: 'sold',
    featured: false,
    images: IMG.apartment.slice(0, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 445,
    saves_count: 29,
  },

  // ─── DHAKA — UTTARA ─────────────────────────────
  {
    title: '[DEMO] Family 3BR Apartment in Uttara Sector 7',
    description: 'Spacious family apartment near Uttara BNS Center. Walking distance to schools and hospitals. Peaceful residential neighborhood.',
    price: 15500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1750,
    city: 'Dhaka',
    location: 'Uttara Sector 7',
    address: 'Road 15, Sector 7, Uttara, Dhaka 1230',
    status: 'available',
    featured: false,
    images: IMG.apartment.slice(2, 5),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 234,
    saves_count: 19,
  },
  {
    title: '[DEMO] 4BR Townhouse in Uttara Sector 13',
    description: 'Modern townhouse with private garden and 2-car garage. 3 floors of comfortable living. Perfect for growing families.',
    price: 35000000,
    price_type: 'sale',
    property_type: 'townhouse',
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3200,
    city: 'Dhaka',
    location: 'Uttara Sector 13',
    address: 'Road 6, Sector 13, Uttara, Dhaka 1230',
    status: 'available',
    featured: false,
    images: IMG.townhouse.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 187,
    saves_count: 15,
  },
  {
    title: '[DEMO] 5 Katha Plot in Uttara Sector 18',
    description: 'Corner plot in upcoming Sector 18. RAJUK approved. All utilities available. Excellent investment opportunity in fast-developing area.',
    price: 22000000,
    price_type: 'sale',
    property_type: 'plot',
    bedrooms: null,
    bathrooms: null,
    area_sqft: 3600,
    city: 'Dhaka',
    location: 'Uttara Sector 18',
    address: 'Sector 18, Uttara, Dhaka 1230',
    status: 'available',
    featured: false,
    images: IMG.plot.slice(0, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 98,
    saves_count: 7,
  },

  // ─── DHAKA — MIRPUR / MOHAMMADPUR ─────────────────────────────
  {
    title: '[DEMO] 3BR Apartment in Mirpur DOHS',
    description: 'Modern apartment in secure DOHS community. Community amenities include mosque, park, and shopping center. Great value for money.',
    price: 12500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1600,
    city: 'Dhaka',
    location: 'Mirpur DOHS',
    address: 'Avenue 3, Mirpur DOHS, Dhaka 1216',
    status: 'available',
    featured: false,
    images: IMG.apartment.slice(1, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 156,
    saves_count: 11,
  },
  {
    title: '[DEMO] 2BR Rental in Mohammadpur',
    description: 'Affordable and spacious rental near Mohammadpur Town Hall. Good transport connectivity. Ideal for small families.',
    price: 28000,
    price_type: 'rent',
    property_type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1100,
    city: 'Dhaka',
    location: 'Mohammadpur',
    address: 'Ring Road, Mohammadpur, Dhaka 1207',
    status: 'available',
    featured: false,
    images: IMG.apartment.slice(4, 6),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 267,
    saves_count: 22,
  },

  // ─── CHITTAGONG ─────────────────────────────
  {
    title: '[DEMO] Sea-View 4BR Apartment in Agrabad',
    description: 'Rare sea-view apartment in Chittagong CBD. Panoramic views of Bay of Bengal. Walking distance to Chittagong Port and business district.',
    price: 38000000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 2600,
    city: 'Chittagong',
    location: 'Agrabad',
    address: 'CDA Avenue, Agrabad, Chittagong 4100',
    status: 'available',
    featured: true,
    images: IMG.apartment.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 512,
    saves_count: 44,
  },
  {
    title: '[DEMO] Luxury Villa in GEC Circle',
    description: 'Elegant villa in prime Chittagong location. Private pool, garden, and rooftop terrace. Close to top schools and hospitals.',
    price: 95000000,
    price_type: 'sale',
    property_type: 'villa',
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 5200,
    city: 'Chittagong',
    location: 'GEC Circle',
    address: 'GEC Circle, Chittagong 4000',
    status: 'available',
    featured: true,
    images: IMG.villa.slice(2, 5),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 678,
    saves_count: 52,
  },
  {
    title: '[DEMO] 3BR Apartment in Nasirabad',
    description: 'Modern family apartment in peaceful Nasirabad Housing Society. Close to CDA Avenue, schools, and shopping areas.',
    price: 14500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1900,
    city: 'Chittagong',
    location: 'Nasirabad',
    address: 'Nasirabad Housing Society, Chittagong 4000',
    status: 'available',
    featured: false,
    images: IMG.apartment.slice(3, 5),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 203,
    saves_count: 17,
  },
  {
    title: '[DEMO] Commercial Office in Khulshi',
    description: 'Modern commercial office in Khulshi. Perfect for corporate offices, banks, or consultancies. Fully air-conditioned with backup generator.',
    price: 650000,
    price_type: 'rent',
    property_type: 'office',
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 2800,
    city: 'Chittagong',
    location: 'Khulshi',
    address: 'Zakir Hossain Road, Khulshi, Chittagong 4225',
    status: 'available',
    featured: false,
    images: IMG.office.slice(0, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 89,
    saves_count: 6,
  },
  {
    title: '[DEMO] Townhouse in Panchlaish',
    description: 'Beautiful 4-bedroom townhouse in family-oriented Panchlaish neighborhood. Includes garden, garage, and servant quarters.',
    price: 42000000,
    price_type: 'sale',
    property_type: 'townhouse',
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3400,
    city: 'Chittagong',
    location: 'Panchlaish',
    address: 'Road 2, Panchlaish, Chittagong 4203',
    status: 'sold',
    featured: false,
    images: IMG.townhouse.slice(0, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 334,
    saves_count: 25,
  },

  // ─── RANGPUR ─────────────────────────────
  {
    title: '[DEMO] Modern 3BR Apartment near Medical More',
    description: 'Newly built apartment near Rangpur Medical College. Perfect for doctors and medical professionals. Walking distance to major hospitals.',
    price: 8500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1800,
    city: 'Rangpur',
    location: 'Medical More',
    address: 'Medical More, Rangpur 5400',
    status: 'available',
    featured: true,
    images: IMG.apartment.slice(0, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 267,
    saves_count: 24,
  },
  {
    title: '[DEMO] Family Villa in Jahaj Company More',
    description: 'Spacious villa with garden in prime Jahaj Company area. Traditional Bengali architecture with modern amenities. 6 bedrooms suitable for large family.',
    price: 22000000,
    price_type: 'sale',
    property_type: 'villa',
    bedrooms: 6,
    bathrooms: 5,
    area_sqft: 4800,
    city: 'Rangpur',
    location: 'Jahaj Company More',
    address: 'Jahaj Company More, Rangpur 5400',
    status: 'available',
    featured: true,
    images: IMG.villa.slice(3, 6),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 389,
    saves_count: 31,
  },
  {
    title: '[DEMO] 2BR Apartment in Dhap',
    description: 'Affordable modern apartment in developing Dhap area. Good for young families. Close to schools and local markets.',
    price: 15000,
    price_type: 'rent',
    property_type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 950,
    city: 'Rangpur',
    location: 'Dhap',
    address: 'Dhap, Rangpur 5400',
    status: 'rented',
    featured: false,
    images: IMG.apartment.slice(2, 4),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 145,
    saves_count: 10,
  },
  {
    title: '[DEMO] 10 Katha Plot in RK Road',
    description: 'Prime commercial-residential plot on RK Road, Rangpur. Excellent for building apartment complex or commercial project. All papers clear.',
    price: 15000000,
    price_type: 'sale',
    property_type: 'plot',
    bedrooms: null,
    bathrooms: null,
    area_sqft: 7200,
    city: 'Rangpur',
    location: 'RK Road',
    address: 'RK Road, Rangpur 5400',
    status: 'available',
    featured: false,
    images: IMG.plot.slice(1, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 78,
    saves_count: 8,
  },
  {
    title: '[DEMO] Studio Apartment near Carmichael College',
    description: 'Compact studio ideal for students. Furnished with basic amenities. Walking distance to Carmichael College and city center.',
    price: 8000,
    price_type: 'rent',
    property_type: 'studio',
    bedrooms: null,
    bathrooms: 1,
    area_sqft: 450,
    city: 'Rangpur',
    location: 'Lalbagh',
    address: 'Lalbagh, Rangpur 5400',
    status: 'available',
    featured: false,
    images: IMG.studio.slice(1, 3),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 112,
    saves_count: 9,
  },

  // ─── ARCHIVED SAMPLES ─────────────────────────────
  {
    title: '[DEMO] Old 2BR Apartment in Old Dhaka',
    description: 'Historic apartment in Old Dhaka. Previously rented. Currently archived pending renovation decision.',
    price: 6500000,
    price_type: 'sale',
    property_type: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area_sqft: 900,
    city: 'Dhaka',
    location: 'Wari',
    address: 'Rankin Street, Wari, Dhaka 1203',
    status: 'archived',
    featured: false,
    images: IMG.apartment.slice(1, 2),
    video_url: null,
    video_type: null,
    whatsapp_number: WA,
    phone_number: PHONE,
    views_count: 45,
    saves_count: 2,
  },
]